CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        description TEXT NOT NULL,
                                        created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        user_id BIGINT NOT NULL,

                                        CONSTRAINT fk_request_to_user
                                        FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_request_requestor ON requests (user_id);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    available BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    request_id BIGINT,
    CONSTRAINT fk_item_to_users
    FOREIGN KEY (user_id)
    REFERENCES users (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT fk_item_to_request
    FOREIGN KEY (request_id)
    REFERENCES requests (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_item_available ON items (available);
CREATE INDEX IF NOT EXISTS idx_item_request ON items (request_id);
CREATE INDEX IF NOT EXISTS idx_item_user ON items (user_id);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_comment_item
    FOREIGN KEY (item_id)
    REFERENCES items (id)
                      ON DELETE RESTRICT
                      ON UPDATE RESTRICT,

    CONSTRAINT fk_comment_user
    FOREIGN KEY (user_id)
    REFERENCES users (id)
                      ON DELETE RESTRICT
                      ON UPDATE RESTRICT
    );

CREATE INDEX IF NOT EXISTS idx_comment_item ON comments (item_id);
CREATE INDEX IF NOT EXISTS idx_comment_user ON comments (user_id);

CREATE TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        finish TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        user_id BIGINT NOT NULL,
                                        status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_booking_to_items
    FOREIGN KEY (item_id)
    REFERENCES items (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT fk_booking_to_users
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_booking_item ON bookings (item_id);
CREATE INDEX IF NOT EXISTS idx_booking_user ON bookings (user_id);
CREATE INDEX IF NOT EXISTS idx_booking_status ON bookings (status);